### PR TITLE
Test Scaffolding/Infrastructure in place 

### LINKED ISSUE #19: add unit tests
## Checklist
Add unit tests for the commands offered by the cli

### PR DESCRIPTION
**Pull request by JacobMGEvans**
- Tests haven't been written out yet but the configurations and libraries are in place.

Will resolve #19 when finished.

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
Will likely close #19 when finished.

**Comment by abhijithvijayan** [comment]
@JacobMGEvans Thanks for the PR. Should I merge this now or wait for the commits with Tests?

**Comment by JacobMGEvans** [comment]
I am ok with you merging it now I can work on it and make another PR later this evening as well. 

The tests now run at least the Babel was needed for some reason but the configuration is now all set for anyone to start plugging away at some tests :)

**Comment by JacobMGEvans** [comment]
Sorry I dont have more done by now, I spread myself thin with several other OSS projects including my own this week 🤣

**Comment by abhijithvijayan** [comment]
@JacobMGEvans It's fine. Whenever you are ready. Thanks.

**Pull request merged**
